<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LocationValueClick</name>
   <tag></tag>
   <elementGuidId>ae18e281-815a-4ee7-86ac-ab142c6cd6c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//ul[@class='select2-results']//div[contains(.,'Paris')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//ul[@class='select2-results']//div[contains(.,'Paris')])[1]</value>
   </webElementProperties>
</WebElementEntity>
