<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectTourType</name>
   <tag></tag>
   <elementGuidId>26d8e66e-cc39-4223-b37f-044f23b91a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li/div[@class=&quot;select2-result-label&quot;][contains(.,'${type}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li/div[@class=&quot;select2-result-label&quot;][contains(.,'${type}')]</value>
   </webElementProperties>
</WebElementEntity>
